apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: rentbook
  labels:
    app: gateway
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: gateway