apiVersion: apps/v1
kind: Deployment
metadata:
  name: Alert
  labels:
    app: Alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Alert
  template:
    metadata:
      labels:
        app: Alert
    spec:
      containers:
        - name: Alert
          image: username/Alert:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5