apiVersion: apps/v1
kind: Deployment
metadata:
  name: Point
  labels:
    app: Point
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Point
  template:
    metadata:
      labels:
        app: Point
    spec:
      containers:
        - name: Point
          image: username/Point:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5