server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Rental
          uri: http://localhost:8081
          predicates:
            - Path=/rentals/** 
        - id: Book
          uri: http://localhost:8082
          predicates:
            - Path=/books/** 
        - id: Payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: Alert
          uri: http://localhost:8084
          predicates:
            - Path=/alerts/** 
        - id: View
          uri: http://localhost:8085
          predicates:
            - Path= /mypages/**
        - id: Point
          uri: http://localhost:8086
          predicates:
            - Path=/points/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Rental
          uri: http://Rental:8080
          predicates:
            - Path=/rentals/** 
        - id: Book
          uri: http://Book:8080
          predicates:
            - Path=/books/** 
        - id: Payment
          uri: http://Payment:8080
          predicates:
            - Path=/payments/** 
        - id: Alert
          uri: http://Alert:8080
          predicates:
            - Path=/alerts/** 
        - id: View
          uri: http://View:8080
          predicates:
            - Path= /mypages/**
        - id: Point
          uri: http://Point:8080
          predicates:
            - Path=/points/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080