apiVersion: apps/v1
kind: Deployment
metadata:
  name: Book
  labels:
    app: Book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Book
  template:
    metadata:
      labels:
        app: Book
    spec:
      containers:
        - name: Book
          image: username/Book:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5