apiVersion: apps/v1
kind: Deployment
metadata:
  name: Rental
  labels:
    app: Rental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Rental
  template:
    metadata:
      labels:
        app: Rental
    spec:
      containers:
        - name: Rental
          image: username/Rental:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5